Taller.App/Taller.App.Front/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Taller.App.Front.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}


Taller.App/Taller.App.Front/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Taller.App.Front.Pages;

public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;

    public IndexModel(ILogger<IndexModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {

    }
}

Taller.App/Taller.App.Front/Pages/Mecanicos/GestionMecanico.cshtml.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Taller.App.Persistencia;
using Taller.App.Dominio.Entidades;

namespace Taller.App.Front.Pages
{
    public class GestionMecanicoModel : PageModel
    {
        private static RepositorioMecanico repoMecanico = new RepositorioMecanico(
          new Persistencia.ContextDb()
      );

        private static RepositorioRevision repoRevision = new RepositorioRevision(
            new Persistencia.ContextDb()
        );

        public string titulo { get; set; } = "";

        public List<Mecanico> listaMecanicos = new List<Mecanico>();

        public Mecanico mecanicoActual;

        public void OnGet()
        {
            this.ObtenerMecanicos();
        }


        public void OnPostAdd(Mecanico mecanico)
        {
            try
            {
                repoMecanico.AgregarMecanico(mecanico);
                this.ObtenerMecanicos();
            }
            catch (System.Exception)
            {

                throw;
            }

        }

        public void OnPostAddRevision(Revision revision)
        {
            try
            {
                // var mecanico = repoMecanico.BuscarMecanico(revision.MecanicoId);
                // revision.Mecanico = mecanico;
                repoRevision.AgregarRevision(revision);
                this.ObtenerMecanicos();
            }
            catch (System.Exception)
            {

                throw;
            }

        }



        public void OnPostDelete(string id)
        {
            try
            {
                repoMecanico.EliminarMecanico(id);
                this.ObtenerMecanicos();
            }
            catch (System.Exception)
            {

                throw;
            }

        }

        private void ObtenerMecanicos()
        {
            // Console.WriteLine("prueba: " + repoMecanico.ObtenerMecanicos());

            foreach (Mecanico mecanico in repoMecanico.ObtenerMecanicos())
            {
                this.listaMecanicos.Add(new Mecanico()
                {
                    MecanicoId = mecanico.MecanicoId,
                    NivelEstudio = mecanico.NivelEstudio,
                    Nombre = mecanico.Nombre,
                    Telefono = mecanico.Telefono,
                    Rol = mecanico.Rol,
                    Contrasenia = mecanico.Contrasenia,
                    FechaNacimiento = mecanico.FechaNacimiento
                });
            }
        }
    }


}

Taller.App/Taller.App.Front/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Taller.App.Front.Pages;

public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}


Taller.App/Taller.App.Front/Pages/Propietario/RegistroPropietario.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Taller.App.Front.Pages
{
    public class RegistroPropietarioModel : PageModel
    {

        public List<String> ciudades = new List<String>(){
            "Bogotá", "Medellín", "Manizales", "Barranquilla"
        };

        public void OnGet()
        {
        }
    }
}

Taller.App/Taller.App.Front/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Taller.App/Taller.App.Front/Pages/Mecanicos/GestionMecanico.cshtml
@page
@model Taller.App.Front.Pages.GestionMecanicoModel
@{
}

<div class="class-contain-title">
    <span>
        Lista mecánicos
    </span>
    <i class="bi bi-plus-circle-fill class-icon-add" title="Agregar mecánico" data-bs-toggle="modal"
        data-bs-target="#idModalMecanico" data-bs-whatever="@@mdo"></i>

    @* <form class="form-inline" style="display: flex; gap: 10px; position: absolute; right: 75px;">
        <input class="form-control mr-sm-2" type="search" placeholder="Buscar" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
        </form> *@
</div>


<table class="table">
    <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Nombre</th>
            <th scope="col">Télefono</th>
            <th scope="col">Rol</th>
            <th scope="col">Acciones</th>
        </tr>
    </thead>
    <tbody>

        @foreach (var m in @Model.listaMecanicos)
        {
            <tr>
                <td>@m.MecanicoId</td>
                <td>@m.Nombre</td>
                <td>@m.Telefono</td>
                <td>@m.Rol</td>
                <td style="display: flex;">
                    <i class="bi bi-pencil-fill class-icon-edi"></i>
                    <form method="POST">
                        <button class="bi bi-trash3-fill class-icon-del" asp-route-id="@m.MecanicoId"
                        asp-page-handler="Delete" type="submit">
                        </button>
                    </form>

                </td>
            </tr>
        }

    </tbody>
</table>


<div class="modal fade" id="idModalMecanico" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Agregar mecánico</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="post">

                    <div class="row">
                        <div class="mb-3 col-6">
                            <label for="idmecanico" class="col-form-label">Id:</label>
                            <input type="text" class="form-control" id="idmecanico" name="MecanicoId"
                                asp-for="@Model.mecanicoActual.MecanicoId">
                        </div>

                        <div class="mb-3 col-6">
                            <label for="nombremecanico" class="col-form-label">Nombre:</label>
                            <input type="text" class="form-control" id="nombremecanico"
                                asp-for="@Model.mecanicoActual.Nombre" name="Nombre">
                        </div>
                    </div>

                    <div class="row">
                        <div class="mb-3 col-6">
                            <label for="idtelefono" class="col-form-label">Teléfono:</label>
                            <input type="text" class="form-control" id="idtelefono"
                                asp-for="@Model.mecanicoActual.Telefono" name="Telefono">
                        </div>

                        <div class="mb-3 col-6">
                            <label for="nivelestudio" class="col-form-label">Nivel de estudio:</label>
                            <select class="form-select" aria-label="Default select example"
                                asp-for="@Model.mecanicoActual.NivelEstudio" name="NivelEstudio">
                                @* <option selected>Open this select menu</option> *@
                                <option value="1">Bachiller</option>
                                <option value="2">Técnico</option>
                                <option value="3">Profesional</option>
                            </select>
                        </div>
                    </div>

                    <div class="row">
                        <div class="mb-3 col-6">
                            <label for="idfecha" class="col-form-label">Fecha nacimiento:</label>
                            <input type="date" class="form-control" id="idfecha"
                                asp-for="@Model.mecanicoActual.FechaNacimiento" name="FechaNacimiento">
                        </div>

                        <div class="mb-3 col-6">
                            <label for="contrasenia" class="col-form-label">Contraseña:</label>
                            <input type="password" class="form-control" id="contrasenia"
                                asp-for="@Model.mecanicoActual.Contrasenia" name="Contrasenia">
                        </div>
                    </div>

                    <div class="row">
                        <div class="mb-3 col-6">
                            <label for="rol" class="col-form-label">Rol:</label>
                            <input type="text" class="form-control" id="rol" name="Rol">
                        </div>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>

                        <button type="submit" class="btn btn-primary" asp-page-handler="Add">Agregar</button>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>



<div class="modal-body">
    <form method="post">

        <div class="row">
            <div class="mb-3 col-4">
                <label for="idmecanico" class="col-form-label">Mecanico:</label>
                <select class="form-select" aria-label="Default select example" name="MecanicoId">
                    @foreach (var m in @Model.listaMecanicos)
                    {
                        <option value="@m.MecanicoId">@m.Nombre</option>
                    }
                </select>
            </div>

            <div class="mb-3 col-4">
                <label for="idrevision" class="col-form-label">Id Revisión:</label>
                <input type="text" class="form-control" id="idrevision" name="RevisionId">
            </div>

            <div class="mb-3 col-4">
                <label for="idfecharevision" class="col-form-label">Fecha:</label>
                <input type="date" class="form-control" id="idfecharevision" name="Fecha">
            </div>
        </div>



        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>

            <button type="submit" class="btn btn-primary" asp-page-handler="AddRevision">Agregar</button>
        </div>
    </form>
</div>

Taller.App/Taller.App.Front/Pages/Propietario/RegistroPropietario.cshtml
@page
@model Taller.App.Front.Pages.RegistroPropietarioModel
@{
}


<form action="">

    <h3>Datos propietario</h3>

    <div class="d-flex flex-row mb-3">
        <div class="mb-3 me-3">
            <label for="exampleFormControlInput1" class="form-label">Cédula</label>
            <input type="number" class="form-control" id="exampleFormControlInput1" placeholder="">
        </div>
        <div class="mb-3 me-3">
            <label for="exampleFormControlTextarea1" class="form-label">Nombre</label>
            <input type="text" class="form-control" id="exampleFormControlTextarea1" rows="3">
        </div>

        <div class="dropdown">
            <label for="exampleFormControlInput1" class="form-label">Ciudad</label>

            <select class="form-select" aria-label="Default select example">
                <option selected>Seleccione</option>
                @foreach (string item in Model.ciudades)
                {
                    <option value="3">@item</option>
                }
            </select>
        </div>
    </div>




    <hr class="border border-primary border-3 opacity-75">

    <h3>Datos Vehículo</h3>


    <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">Placa</label>
        <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
    </div>
    <div class="mb-3">
        <label for="exampleFormControlTextarea1" class="form-label">Modelo</label>
        <input type="number" class="form-control" id="exampleFormControlTextarea1" rows="3">
    </div>


</form>

Taller.App/Taller.App.Front/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Taller.App.Front</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/Taller.App.Front.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Bienvenidos G8</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area=""
                                asp-page="/Mecanicos/GestionMecanico">Mecánicos</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area=""
                                asp-page="/Propietario/RegistroPropietario">Registro Propietario</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Taller.App.Front - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>